#cgates/jebene: 7/9/2014
#cgates/jebene: 3/30/2015

language: python
python:
    - "2.7"
    - "3.4"

install:
    - pip install -r requirements.txt

before_script:
    - pip install coverage
    - pip install coveralls

script:
    - nosetests --with-coverage --verbose --cover-package=jacquard
    - nosetests examples

after_success:
    - coveralls

notifications:
    email:
        - cgates@umich.edu
